Repository atlp-rwanda/Dev-Pulse-FN, pull requests merged in 2021-09, with the labels that each got.

#23 fix profile error
  src/components/rate/ManageRatingsPage.js
  src/components/shared/ChangeProgram.js
Labels: ready, fix

#19 feature: cohort and programs crud
  src/actions/EngineerActions.js
  src/actions/actionType.js
  src/components/AdminDashboard.js
  src/components/App.js
  src/components/ManageCohorts.js
  src/components/shared/CohortDropDown.js
  src/components/shared/InputTags.js
  src/components/shared/admin/AddCohort.js
  src/components/shared/admin/EachProgram.js
  src/index.js
  src/reducers/EngineerReducer.js
  src/styles/App.css
  src/styles/admin.style.scss
Labels: ready, Feature

#27 fixing some errors in production
  public/dev_pulse.png
  public/index.html
  src/actions/emailList.js
  src/components/shared/Header.js
  src/components/shared/admin/addEmails.js
  src/components/shared/admin/removeEmails.js
Labels: ready

#30 fix(addList):redirect on add or remove engineer on my list
  src/components/egineerList.js
  src/styles/list.scss
Labels: ready, fix

#32 fixes the average row issue
  src/actions/EngineerActions.js
Labels: ready, fix

#29 fix(programs): update submit & cursor change
  src/components/shared/admin/EachProgram.js
  src/styles/App.scss
  src/styles/authLogin.scss
Labels: ready, fix

#33 chore(node version): updating node version
  .babelrc
  package.json
  src/tests/getEngineers.test.js
  webpack.config.dev.js
  webpack.config.js
Labels: ready
