Repository atlp-rwanda/Dev-Pulse-FN, pull requests merged in 2021-08, with the labels that each got.

#10 feature(filtering): engineers & ratings filter
  src/actions/EngineerActions.js
  src/actions/actionType.js
  src/actions/engineerList.js
  src/actions/getEngineers.js
  src/components/HomePage.js
  src/components/shared/ChangeCohort.js
  src/components/shared/ChangeProgram.js
  src/components/shared/CohortDropDown.js
  src/components/shared/ProgramDropDown.js
  src/components/singleEngineer.js
  src/components/table.js
  src/components/tableContent.js
  src/reducers/EngineerReducer.js
  src/reducers/engineerList.js
  src/styles/list.scss
  src/styles/singleEngingeer.scss
  src/styles/table.scss
Labels: ready

#13 feat(ratings): update average if program change
  src/components/singleEngineer.js
  src/reducers/EngineerReducer.js
Labels: ready, Feature

#15 Ch change program
  src/actions/EngineerActions.js
  src/actions/actionType.js
  src/actions/authAction.js
  src/actions/engineerAction.js
  src/actions/fetchProfile.js
  src/components/AuthPage.js
  src/components/shared/ChangeCohort.js
  src/components/shared/ChangeProgram.js
  src/components/shared/CohortDropDown.js
  src/components/shared/ProgramDropDown.js
  src/components/singleEngineer.js
  src/components/table.js
  src/reducers/EngineerReducer.js
Labels: ready, chore

#14 admin dashboard
  package.json
  src/actions/actionType.js
  src/actions/emailList.js
  src/components/AdminDashboard.js
  src/components/App.js
  src/components/AuthorizeEmails.js
  src/components/shared/DeleteConfirmPopup.js
  src/components/shared/Header.js
  src/components/shared/InputTags.js
  src/components/shared/SnackBarMessage.js
  src/components/shared/admin/addEmails.js
  src/components/shared/admin/removeEmails.js
  src/index.js
  src/reducers/emailListReducer.js
  src/reducers/index.js
  src/styles/admin.style.scss
  src/styles/inputTags.scss
Labels: ready

#17 setup heroku CD
  .gitignore
  package.json
  server.js
  src/api/usersApi.js
  src/components/AuthPage.js
  src/components/rate/ManageRatingsPage.js
  webpack.config.js
Labels: ready

#16 feature: engineer rating button
  src/components/egineerList.js
  src/components/singleEngineer.js
Labels: ready, Feature

#18 fix(cohorts): fetch cohorts on on hover dropdown
  src/actions/EngineerActions.js
  src/components/AdminDashboard.js
  src/components/AuthorizeEmails.js
  src/components/shared/SnackBarMessage.js
  src/components/shared/admin/removeEmails.js
Labels: ready
